ARG version=9
FROM almalinux:${version}
ARG COURSE
ARG TRAINER
ENV COURSE=${COURSE}
ENV TRAINER=${TRAINER}
RUN echo "welcome to hyd" > /tmp/rakesh.txt
RUN echo "Course is: ${COURSE}, trainer is: ${TRAINER}"
RUN echo "welcome to version ${version}"
RUN echo "welcome to hyd" > /tmp/rakesh.txt
